---
title: "Green_Frog_Sampel"
format: html
editor: visual
---

## Load Packages
```{r}
#| output: false
if (!require(librarian)){
  install.packages("librarian")
  library(librarian)
}

librarian::shelf(tidyverse, RPostgres, DBI, unmarked, here, lubridate, kableExtra, GGally, MuMIn, AHMbook, AICcmodavg)

```

## CMR RV Pond - clamitans
```{r}
green_mid_clean_up <- cmr_raw_data %>% 
  filter(species_capture == "rana_clamitans",
         site == "rv_pond") %>% 
  select(!c(capture_type)) %>% 
  unite(species_capture, c(species_capture, cmr_id), sep = "_")
  
green_pop_zeros <- cmr_raw_visits %>% 
  filter(site == "rv_pond") %>% 
  left_join(gree_mid_clean_up) %>%
  complete(nesting(date, site), 
           fill = list(n = 0)) %>% 
  ungroup() %>% 
  group_by(site) %>% 
  mutate(n_visit = match(date, unique(date)),
         n_visit = paste0("visit_", n_visit, sep = "")) %>% 
  select(!date) %>% 
  ungroup()

remove_4_6 <- green_pop_zeros %>%
  filter(n_visit %in% c("visit_4", "visit_5", "visit_6")) %>%
  mutate(site = if_else(site == "rv_pond", "rv_pond_2", site),
         n_visit = if_else(n_visit == "visit_4", "visit_1", n_visit),
         n_visit = if_else(n_visit == "visit_5", "visit_2", n_visit),
         n_visit = if_else(n_visit == "visit_6", "visit_3", n_visit))

green_pop_zeros <- green_pop_zeros %>%
  filter(!n_visit %in% c("visit_4", "visit_5", "visit_6"))


green_pop_zeros <- rbind(green_pop_zeros,remove_4_6)

clean_green <- green_pop_zeros %>%   
  group_by(site, species_capture, n_visit) %>% 
  reframe(n = n()) %>% 
  mutate(n = if_else(is.na(species_capture), NA, n)) %>% 
  pivot_wider(names_from = c("n_visit"), values_from = c("n")) %>%
  drop_na(species_capture) %>%
  unite(species_capture, c("site", "species_capture"), sep = "_", na.rm = T) %>% 
  mutate_all(~replace_na(.,0)) 

write_csv(clean_green, here("RVpond_clean_green.csv"))

clean_green_3 <- clean_green

clean_green_3$captureHistory <- paste(clean_green$visit_1, clean_green$visit_2, clean_green$visit_3,
                               sep = "")


lev <- unique(clean_green_3$captureHistory)

clean_green_3$captureHistory <- factor(clean_green_3$captureHistory, levels = lev)

clean_green_3 <- table(clean_green_3$species_capture, clean_green_3$captureHistory)
  

class(clean_green_3) <- "matrix"

o2y <- matrix(1, 3, 3)

crPiFun <- function(p) {
    p1 <- p[,1]
    p2 <- p[,2]
    p3 <- p[,3]

    cbind("100" = (1-p1) * p2 * p3,        #1: 100    
          "110" = (1-p1) * (1-p2) * p3,    #2: 110
          "001" =  p1 * p2 * (1-p3)       #001
          
          
    )
}


umf_3 <- unmarkedFrameMPois(y = clean_green_3, piFun = "crPiFun", obsToY = o2y)

fm_3 <- multinomPois(~1 ~1, umf_3, engine = "R")

backTransform(fm_3, "state")
backTransform(fm_3, "det") 
```

## CMR all sites - clamitans
```{r}
green_mid_clean_up <- cmr_raw_data %>% 
  filter(species_capture == "rana_clamitans") %>% 
  select(!c(capture_type)) %>% 
  unite(species_capture, c(species_capture, cmr_id), sep = "_")
  
green_pop_zeros <- cmr_raw_visits %>% 
  #filter(site == "rv_pond") %>% 
  left_join(green_mid_clean_up) %>%
  complete(nesting(date, site), 
           fill = list(n = 0)) %>% 
  ungroup() %>% 
  group_by(site) %>% 
  mutate(n_visit = match(date, unique(date)),
         n_visit = paste0("visit_", n_visit, sep = "")) %>% 
  select(!date) %>% 
  ungroup()

remove_4_6 <- green_pop_zeros %>%
  filter(n_visit %in% c("visit_4", "visit_5", "visit_6")) %>%
  mutate(site = if_else(site == "rv_pond", "rv_pond_2", site),
         n_visit = if_else(n_visit == "visit_4", "visit_1", n_visit),
         n_visit = if_else(n_visit == "visit_5", "visit_2", n_visit),
         n_visit = if_else(n_visit == "visit_6", "visit_3", n_visit))

green_pop_zeros <- green_pop_zeros %>%
  filter(!n_visit %in% c("visit_4", "visit_5", "visit_6")) %>% 
  group_by(site, species_capture, n_visit) %>% 
  unique()


green_pop_zeros <- rbind(green_pop_zeros,remove_4_6)

clean_green <- green_pop_zeros %>%   
  group_by(site, species_capture, n_visit) %>% 
  reframe(n = n()) %>% 
  mutate(n = if_else(is.na(species_capture), NA, n)) %>% 
  pivot_wider(names_from = c("n_visit"), values_from = c("n")) %>%
  drop_na(species_capture) %>%
  unite(species_capture, c("site", "species_capture"), sep = "_", na.rm = T) %>% 
  mutate_all(~replace_na(.,0)) 

write_csv(clean_green, here("all_sites_clean_green.csv"))

clean_green_3 <- clean_green

clean_green_3$captureHistory <- paste(clean_green$visit_1, clean_green$visit_2, clean_green$visit_3,
                               sep = "")


lev <- unique(clean_green_3$captureHistory)

clean_green_3$captureHistory <- factor(clean_green_3$captureHistory, levels = lev)

clean_green_3 <- table(clean_green_3$species_capture, clean_green_3$captureHistory)
  

class(clean_green_3) <- "matrix"

o2y <- matrix(1, 3, 4)

crPiFun <- function(p) {
    p1 <- p[,1]
    p2 <- p[,2]
    p3 <- p[,3]

    cbind("010" = (1-p1) * p2 * (1-p3),        #1: 010    
          "100" = (1-p1) * p2 * p3,             #2: 100
          "110" =  (1-p1) * (1-p2) * p3,        #110
          "001" = p1 * p2 * (1-p3)              #001
          
          
    )
}


umf_3 <- unmarkedFrameMPois(y = clean_green_3, piFun = "crPiFun", obsToY = o2y)

fm_3 <- multinomPois(~1 ~1, umf_3, engine = "R")

backTransform(fm_3, "state")
backTransform(fm_3, "det") 
```